export const COUNTY_COLOURS = {
  Antrim:      { primary: '#FFD700', secondary: '#FFFFFF' },
  Armagh:      { primary: '#FF6600', secondary: '#FFFFFF' },
  Carlow:      { primary: '#CC0000', secondary: '#FFD700' },
  Cavan:       { primary: '#003DA5', secondary: '#FFFFFF' },
  Clare:       { primary: '#FFD700', secondary: '#003DA5' },
  Cork:        { primary: '#CC0000', secondary: '#FFFFFF' },
  Derry:       { primary: '#CC0000', secondary: '#FFFFFF' },
  Donegal:     { primary: '#FFD700', secondary: '#006633' },
  Down:        { primary: '#CC0000', secondary: '#FFFF00' },
  Dublin:      { primary: '#003DA5', secondary: '#FFFFFF' },
  Fermanagh:   { primary: '#006633', secondary: '#FFFFFF' },
  Galway:      { primary: '#8B0000', secondary: '#FFFFFF' },
  Kerry:       { primary: '#006633', secondary: '#FFD700' },
  Kildare:     { primary: '#FFFFFF', secondary: '#CC0000' },
  Kilkenny:    { primary: '#000000', secondary: '#FFD700' },
  Laois:       { primary: '#003DA5', secondary: '#FFFFFF' },
  Leitrim:     { primary: '#006633', secondary: '#FFD700' },
  Limerick:    { primary: '#006633', secondary: '#FFFFFF' },
  Longford:    { primary: '#003DA5', secondary: '#FFD700' },
  Louth:       { primary: '#CC0000', secondary: '#FFFFFF' },
  Mayo:        { primary: '#006633', secondary: '#CC0000' },
  Meath:       { primary: '#006633', secondary: '#FFD700' },
  Monaghan:    { primary: '#FFFFFF', secondary: '#003DA5' },
  Offaly:      { primary: '#006633', secondary: '#FFD700' },
  Roscommon:   { primary: '#FFD700', secondary: '#003DA5' },
  Sligo:       { primary: '#000000', secondary: '#FFFFFF' },
  Tipperary:   { primary: '#003DA5', secondary: '#FFD700' },
  Tyrone:      { primary: '#FFFFFF', secondary: '#CC0000' },
  Waterford:   { primary: '#003DA5', secondary: '#FFFFFF' },
  Westmeath:   { primary: '#8B0000', secondary: '#FFFFFF' },
  Wexford:     { primary: '#8B0000', secondary: '#FFD700' },
  Wicklow:     { primary: '#003DA5', secondary: '#FFD700' },
}

export const ALL_COUNTIES = Object.keys(COUNTY_COLOURS).sort()
